Phase2: Digital river features: Invoice links, manage my cards, tax calculation
vtex-apps/digital-river pull request #45
Opened 2021-11-16 17:43 UTC by aavila-vinneren

This PR contains new features:
1. Invoice links in order details page
2. Manage my credit cards from digital river under my account 
3. Tax calculation inclusive or exclusive

2021-11-16 20:10 UTC, polishq requested changes

2021-11-16 20:28 UTC, polishq requested changes

2021-11-16 20:28 UTC, polishq commented on react/Admin.tsx
> +  }, [data, account, formatMessage, settingsState])
Having `settingsState` in the array here is causing an endless loop bug on the admin page. Basically this is saying that whenever `settingsState` changes, run the above code, but the above code changes `settingsState`. To fix, you can remove `settingsState` from the array on line 68 and change line 67 to this:

```
setSettingsState((prevState) => {
      return { ...prevState, ...parsedSettings }
    })
```

2021-11-16 20:53 UTC, polishq requested changes

2021-11-16 20:53 UTC, polishq commented on node/middlewares/tax.ts
> -      },
Why were these lines removed? It's especially important to include any discounts on the item, or the tax will be calculated incorrectly. I would make sure the items array is being constructed the same as in `middlewares/checkout.ts` to ensure that calculations are consistent.

Additionally, we recently encountered a bug in another app having to do with free gifts. I tested the scenario with this new version of DR and tax was calculated for the free item as if it were being sold at its full price. To handle this, I suggest checking for the `item.isGift` flag and manually setting its price as 0 in the DR array.

2021-11-17 14:42 UTC, aavila-vinneren commented on react/CreditCardsPage.tsx
> +    loadDigitalRiver(parsedSettings.digitalRiverPublicKey)
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on node/middlewares/tax.ts
> -      },
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on react/Admin.tsx
> +  }, [data, account, formatMessage, settingsState])
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on react/Admin.tsx
> +                    (appId !== 'vtexus.connector-digital-river' &&
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on react/Admin.tsx
> +                    })} ${appId}`}
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on node/middlewares/tax.ts
> +      id: '0',
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on node/middlewares/tax.ts
> +        throw new ResolverError({
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on messages/en.json
> +  "admin/digital-river.settings.enableTaxInclusive.helpText": "Activate tax inclusive for tax calculations. WARNING: Make sure to test checkout after changing this setting.",
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on messages/en.json
> +  "admin/digital-river.settings.enableTaxInclusive.label": "Enable tax inclusive",
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on messages/en.json
> +  "admin/digital-river.settings.alert.errorText": "To set digital river as a your payment gateway uninstall the tax provider",
Done!

2021-11-17 14:43 UTC, aavila-vinneren commented on manifest.json
> +  "version": "1.3.1",
Done!

2021-11-17 19:02 UTC, polishq requested changes

2021-11-17 19:02 UTC, polishq commented on react/InvoicesPage.tsx
> +                <div>{`Order date: ${invoice.orderDate}`}</div>
Currently this date is displayed like "2021-08-24T15:58:42.4641087+00:00". Can it be formatted similar to how dates are shown in My Orders?

2021-11-18 18:29 UTC, polishq requested changes

2021-11-18 18:29 UTC, polishq commented on CHANGELOG.md
> +## [2.3.0] - 2021-11-18
Please remove this line, the version number and date will be automatically populated when the PR is merged. For now the changelog should look like: 

```
## [Unreleased]

### Added

- Change 1
- Change 2
- etc
```

2021-11-18 18:29 UTC, polishq commented on docs/README.md
> +3. In the settings fields, enter your `Digital River public key`, `Digital River token`, `VTEX App Key` and `VTEX App Token`. For initial testing, use a test `Digital River token` and leave the `Enab
```suggestion
3. In the settings fields, enter your `Digital River public key`, `Digital River token`, `VTEX App Key` and `VTEX App Token`. For initial testing, use a test `Digital River token` and leave the `Enable production mode` toggle turned off. Turn on the `Enable automatic catalog sync` toggle to enable syncing of SKUs from VTEX to Digital River each time a SKU is added or updated in your VTEX catalog. Turn on the `Enable tax inclusive prices` toggle if your catalog uses tax-inclusive product prices.
```

2021-11-18 18:29 UTC, polishq commented on docs/README.md
> +⚠️ _There should be no other tax calculation provider enabled, if so it will re required to disable it._
```suggestion
⚠️ _Digital River provides its own tax calculation service. Therefore there should be no other tax calculation provider enabled on your account. If there is, you will be required to disable it before Digital River can be configured._
```

2021-11-18 18:29 UTC, polishq commented on react/CreditCardsPage.tsx
> +          }`}</label>
Please use intl here

2021-11-18 18:59 UTC, polishq requested changes

2021-11-18 18:59 UTC, polishq commented on node/middlewares/tax.ts
> +    itemTaxResponse: taxesResponse,
Please log this response body for debugging purposes

2021-11-18 18:59 UTC, polishq commented on node/middlewares/tax.ts
> +    if (checkoutResponse) {
Please log the checkoutResponse here

2021-11-23 20:37 UTC, polishq requested changes

2021-11-23 20:37 UTC, polishq commented on node/middlewares/tax.ts
> +    taxesResponse,
```suggestion
    cacheResponse || taxesResponse,
```

2021-11-23 20:41 UTC, polishq submitted a review, later dismissed

2021-11-23 20:43 UTC, polishq submitted a review, later dismissed

2021-11-23 21:01 UTC, polishq approved these changes

2021-11-23 21:23 UTC, merged