Adding support for billing address in dropin
vtex-apps/digital-river pull request #52
Opened 2021-12-10 11:24 UTC by aavila-vinneren

2022-01-12 15:38 UTC, polishq requested changes

2022-01-12 15:38 UTC, polishq commented on node/middlewares/digitalRiver.ts
> +    if (err.response.status !== 404) {
Shouldn't this be `===` instead of `!==` ?

2022-01-12 20:03 UTC, aavila-vinneren commented on node/middlewares/digitalRiver.ts
> +    if (err.response.status !== 404) {
ooohh you are right, since I couldn't test 404 scenario, but rest worked fine, but yeah will add that

2022-01-14 21:11 UTC, polishq submitted a review, later dismissed

2022-01-14 21:17 UTC, polishq approved these changes

2022-01-14 21:20 UTC, merged