[DIGITALRIV-28][DIGITALRIV-27] Q3 App Review
vtex-apps/digital-river pull request #79
Opened 2022-07-21 19:39 UTC by polishq

As part of our team's 2022 Q3 App Review, this PR:
- Adds the `@checkAdminAccess` GraphQL directive for improved security
- Moves the Digital River admin navigation link to the Transactions section and adds the payment-related `LMProductId` to control admin user access
- Reduces unnecessary logger usage
- Fixes a bug where the app expected the Digital River order state to be `payment_pending` but the actual state is `pending_payment` (all possible order states are now specified in the typings)
- Re-enables automatic retries on HTTP requests; previously these were disabled to prevent duplicate orders being created if the first attempt timed out. Now retries are disabled only on the `createOrder` method.
- Refactors backend code to address SonarCloud warnings and improve optimization (no more await in loop, for example)

This new version has been published as a beta and installed in `sandboxusdev` master. I have tested tax calculation and successfully placed (and settled) a test order.

2022-07-22 17:05 UTC, Arturo777 requested changes

2022-07-22 17:05 UTC, Arturo777 commented on node/resolvers/directives/checkAdminAccess.ts
> +        message: 'Avalara-AttemptedUnauthorizedAccess',
Avalara is related to this logger?

2022-07-22 19:28 UTC, polishq commented on node/resolvers/directives/checkAdminAccess.ts
> +        message: 'Avalara-AttemptedUnauthorizedAccess',
Good catch! Serves me right for copying code. Fixed

2022-07-25 13:57 UTC, whc105 approved these changes
LGTM

2022-07-25 15:17 UTC, Arturo777 approved these changes
LOGM

2022-07-25 15:18 UTC, merged