Feature/cypress
vtex-apps/digital-river pull request #81
Opened 2022-09-05 06:04 UTC by shashidhar85

2022-09-05 07:54 UTC, Syed-Vtex requested changes

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +  // it('add card in account page', updateRetry(2), () => {
Remove commented code

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +      phoneNumber: '(312) 310 3249',
Why we are passing phoneNumber here
Does it mean digitalRiver doesn't work with invalid phone number

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/integration/2.3-order-discount-shipping-in-checkout.spec.js
> +  it('invoice apis', updateRetry(2), () => {
Is it working?
I'm sure it will not work because you are placing it block inside it block

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +  setWorkspaceAndGatewayAffiliations({ wipe: true })
Here you are not wiping tax configuration

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +describe('Setting up affirm in dynamic environment', () => {
please pay attention when you copy testcase from other files

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/support/commands.js
> +Cypress.Commands.add('setOrderItems', (checkItem, checkvalue) => {
I think for this commands we already have code in cy-runner
You don't need here

2022-09-05 07:54 UTC, Syed-Vtex commented on cypress/support/graphql.js
> +import { CONNECTOR_DIGITAL_RIVER } from '../support/graphql_apps'
Check this

2022-09-05 07:56 UTC, Syed-Vtex commented on cy-runner.yml
> +  name: sumandigitalriver
TODO: Update hardcoded strings + update other strings which is required

2022-09-05 07:58 UTC, Syed-Vtex commented on cypress/support/index.js
> +  preserve: /VtexIdclientAutCookie|csrftoken/,
If we preserve like this   **preserve: /VtexIdclientAutCookie|csrftoken/,**
Then we don't need preserveCookies

2022-09-05 07:59 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    prefix: 'singleProduct',
Please remove properties which we are not using 
So, that we can keep code clean

2022-09-05 07:59 UTC, shashidhar85 commented on cypress/integration/2.2-single-product.spec.js
> +      phoneNumber: '(312) 310 3249',
no it works without that also I will remove that

2022-09-05 07:59 UTC, shashidhar85 commented on cypress/integration/2.3-order-discount-shipping-in-checkout.spec.js
> +  it('invoice apis', updateRetry(2), () => {
@saravananvenkatesan please check this.

2022-09-05 08:01 UTC, shashidhar85 commented on cypress/support/index.js
> +  preserve: /VtexIdclientAutCookie|csrftoken/,
I will update

2022-09-05 08:01 UTC, Syed-Vtex requested changes

2022-09-05 08:01 UTC, Syed-Vtex commented on cypress/support/testcase.js
> +export function sendInvoiceTestCase({
Review this whole file and remove the code which is already written
Instead use import

2022-09-06 13:20 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +  setWorkspaceAndGatewayAffiliations({ wipe: true })
@sumanraj123 pls check this

2022-09-06 13:23 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    prefix: 'singleProduct',
@sumanraj123 @shashidhar85 @saravananvenkatesan pls check

2022-09-06 13:23 UTC, Syed-Vtex commented on cypress/support/testcase.js
> +export function sendInvoiceTestCase({
@saravananvenkatesan @shashidhar85 pls check

2022-09-06 13:23 UTC, Syed-Vtex commented on cy-runner.yml
> +  name: sumandigitalriver
@sumanraj123

2022-09-06 13:24 UTC, Syed-Vtex commented on cypress/support/commands.js
> +Cypress.Commands.add('setOrderItems', (checkItem, checkvalue) => {
@sumanraj123 pls check

2022-09-06 13:25 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +describe('Setting up affirm in dynamic environment', () => {
@sumanraj123 pls

2022-09-08 11:11 UTC, shashidhar85 commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
yes when I'm testing in local it is getting failed so I added this.

2022-09-08 11:15 UTC, sumanraj123 commented on cypress/integration/wipe.spec.js
> +  setWorkspaceAndGatewayAffiliations({ wipe: true })
@Syed-Vtex wiped the configuration

2022-09-08 12:15 UTC, Syed-Vtex commented on cypress/support/product.js
> +  coconut: 'Fresh Coconuts',
Remove products which we don't use + add comment 
In which testcase this product is used

2022-09-08 12:16 UTC, Syed-Vtex commented on cypress/support/constants.js
> +export const ENVS = {
Can we move this to its respective file

2022-09-08 12:18 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product.spec.js
> +  // TODO - Please do not remove preserveCookie().
Don't add TODO if we add todo
then in future we will think that we missed some thing

// Digital River adds some cookies which is used in checkout
// So, we need to use preserveCookies() 
// If we remove then digital river payment will not be loaded in checkout

2022-09-08 12:19 UTC, Syed-Vtex commented on cypress/integration/2.2-multi-product.spec.js
> +const orderform = '.orderform.json'
Fix warning

2022-09-08 12:21 UTC, Syed-Vtex commented on cy-runner.yml
> +  name: sumandigitalriver
It is still hardcoded to sumandiigitalriver

@shashidhar85 @sumanraj123

2022-09-08 12:21 UTC, Syed-Vtex commented on cy-runner.yml
> +    board: ''
@shashidhar85 Update board name

2022-09-08 12:21 UTC, Syed-Vtex commented on cy-runner.yml
> +      enabled: false
This should be true for github actions

2022-09-08 12:26 UTC, shashidhar85 commented on cypress/support/constants.js
> +export const ENVS = {
done

2022-09-08 12:26 UTC, Syed-Vtex commented on cypress/integration/2.1-single-product.spec.js
> +      cy.get(digitalRiverSelectors.DigitalRiverCCSubmit).should('be.visible')
Add it as comment

2022-09-08 12:36 UTC, Syed-Vtex commented on cypress/support/graphql.js
> +              appId: 'vtexus.connector-digital-river',
@shashidhar85 Update this to timestamp
i.e new Date()

2022-09-13 11:20 UTC, Syed-Vtex approved these changes

2022-09-13 11:21 UTC, merged